apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-nginx
  labels:
    app: internal-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-nginx
  template:
    metadata:
      labels:
        app: internal-nginx
    spec:
      containers:
      - name: internal-nginx
        image: 241533157276.dkr.ecr.us-east-2.amazonaws.com/internal-nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: internal-nginx
  labels:
    app: internal-nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: internal-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
